#!/bin/sh

if [ $# -ne 2 ]; then
    echo "Usage: $0 data-file initial" >&2
    exit 1
fi

datfile="$1"
lockfile="$1.lck"
initial=$2

(
    flock -x 9
    num=$initial
    if [ -e "$datfile" ]; then
        read -r num < "$datfile"
    fi

    printf $((initial <= num ? 0 : 1))

    max=$((num > initial ? num : initial))
    echo $max > "$datfile"
) 9> "$lockfile"
